### ISSUE TITLE
Can't resolve 'lunr'

### ISSUE THREAD

**Issue by writecleancode** [lelouch77/docusurus-lunr-search#1]
I followed the instructions in the readme file and I get
```
./src/theme/SearchBar/lib/lunar-search.js
Module not found: Can't resolve 'lunr' in '...\_work\docusaurus\my-website\src\theme\SearchBar\lib'chunk 32
32.bafed9d0.js
```
I used docusaurus init and created the sample project. FYI, I am on Windows.

**Comment by lelouch77** [comment]
intstall lunr
```
npm i lunr
```

I missed it package.json ... Will add it ... Thanks @writecleancode

**Comment by writecleancode** [comment]
Thank you.

When I ran `node build-search-data.js`, I got this error.
```
(node:17520) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '....\my-website\src\theme\LunrSearchBar\search-data.js'
(node:17520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The line `const SEARCH_DATA_LOCATION = "./src/theme/LunrSearchBar/search-data.js";` in `build-search-data.js` should be `const SEARCH_DATA_LOCATION = "./src/theme/SearchBar/search-data.js";`. Right?

I am just familiarising myself with github and don't how to create a PR yet. Would you mind changing the file if the error is genuine?

**Comment by lelouch77** [comment]
yes.. thanks ... I will do that...

**Comment by lelouch77** [comment]
Updated the `SEARCH_DATA_LOCATION ` and also published new version with 'lunr' as a dependency 
Thanks..
