### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by ZachJW34** [lelouch77/docusurus-lunr-search#4]
I am integrating local search into my companies DocusaurusV2 website and it seems that the more popular plugins for local search are yours and [cmfcmf's](https://github.com/cmfcmf/docusaurus-search-local). I love the default styling that Aglolia and your package provides, but the build process that cmfcmf implements is cleaner (using the docusaurus postBuild lifecycle to generate the search metadata). Have you considered implementing a similar build process vs the `build-search-data.js` node script?
I'd be willing to contribute if you're interested!

**Comment by lelouch77** [comment]
That's a great idea @ZachJW34,  definitely I will work on it ... And yes I would love to have your contribution.

Thanks.

**Comment by ZachJW34** [comment]
I'll submit a PR for this then!

**Comment by lelouch77** [comment]
Hey, thanks for the PR, for now, I published it in `0.0.7-rc1`, I will run some tests and merge it to master
